name: TikTok Sandik Botu

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/10 * * * *" # Her 10 dakikada bir otomatik çalışıp sandık arar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt
    - name: Botu Başlat
      run: |
        python main.py
        
